language: rust
sudo:     false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libsodium-dev

after_success: |
  [ $TRAVIS_BRANCH       = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ]  &&
  script/update-docs $TRAVIS_REPO_SLUG

env:
  global:
  - secure: acVYyVNOSCGWxvPTsPKPQE6+P1RHyFXGcuRHPQpT3NBkNLB3ezMyufICYJupKNA8aJ5UwUKDp3OTkF9gMdtCUXoXnTLdNxFdUXyIUkiJ4NKgo4Ou1YIEe54TxiBy3M3aU9CbpRqqqTVhJO/K6QqddTBnlXH4avfllqBDzLAS99OW2HZSk0u2RJWupozKcaUjdiDi86Kw8ezMNvF0S7Ql6kB5N/g9TDvYFa0IIp6PmrEmOsm5aQlC+9RupzkQVcVCczoELdyFuJC5TCtyI2HnKoWIviSeLiMXiFBMfRqYlBDe2dCoZxkByWnGcL9YLzgh5GFMgLaW5Jx/NfxzraxG4X4KAcnm/gztP211XtAMGdiPGX9XBbZ1GQKj669S51jgyeUk+NGztk9+RzI93X8aNeHV3jZcgCFHhShZhyaPyn3JGcq2BCfsKuz7ahvU0JL1myeiKs06CqclkLCB7/7RI/NbbP0Pv9TQzAEzHpnZ0vN9gbl7dAZOttFLY7S1clGcKChNNUCfWcrtbYZZxQHMvfAaRD4N8cHslX5Yzfr8bd4jhyORxyuDWCsOE2+Y5+5lODES7BzjWix3LIjBKAbRJ0XXOh7W4OufNOtxoSwIjpQSyUcq7aeZUUsdhIcsNz+J03JRUUmwifKoUwz/OwaimpUNHBykCM5fAQBlHH2FoyU=
